update carve vpc template

diff --git a/src/managed_deployment/carve-vpc-stack.cfn.yml b/src/managed_deployment/carve-vpc-stack.cfn.yml
--- a/src/managed_deployment/carve-vpc-stack.cfn.yml
+++ b/src/managed_deployment/carve-vpc-stack.cfn.yml
@@ -36,6 +36,9 @@ Parameters:
     Description: Desored number of instances in the ASG
     Type: Number
     Default: '1'
+  PublicIPs:
+    Description: Assign Public IPs to Instances
+    Default: 'false'
 
 # Conditions:
 #   UseOrgId: !Equals 
@@ -198,44 +201,8 @@ Resources:
 
   LaunchConfig:
     Type: AWS::AutoScaling::LaunchConfiguration
-    Metadata:
-      AWS::CloudFormation::Init:
-        config:
-          files:
-            # get the carve updater python code from S3 (the location below is replaced in code later)
-            Fn::Transform:
-              Name: AWS::Include
-              Parameters:
-                Location: s3://carve-managed-bucket/managed_deployment/carve-updater.yml
-            # create the carve config file
-            "/carve/carve.cfg":
-              content: "0.0.0.0"
-              mode: "000644"
-              owner: "root"
-              group: "root"                    
-            # The cfn-hup.conf file stores the name of the stack and the AWS credentials that the cfn-hup daemon targets.
-            "/etc/cfn/cfn-hup.conf":
-              content: !Sub |
-                [main]
-                stack=${AWS::StackId}
-                region=${AWS::Region}
-                # The interval used to check for changes to the resource metadata in minutes. Default is 15
-                interval=1
-              mode: "000400"
-              owner: "root"
-              group: "root"
-            # The user actions that the cfn-hup daemon calls periodically are defined in the hooks.conf configuration file.
-            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
-              content: !Sub |
-                [cfn-auto-reloader-hook]
-                triggers=post.update
-                path=Resources.LaunchConfig.Metadata.AWS::CloudFormation::Init
-                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchConfig --region ${AWS::Region}
-              mode: "000400"
-              owner: "root"
-              group: "root"
     Properties:
-      AssociatePublicIpAddress: 'true'
+      AssociatePublicIpAddress: !Ref PublicIPs
       SecurityGroups:
         - !Ref 'InstanceSecurityGroup'
       IamInstanceProfile: !Ref 'InstanceProfile'
@@ -254,9 +221,77 @@ Resources:
           !Sub |
             #!/bin/bash -xe
             # Start cfn-init
-            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r LaunchConfig --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
+            # /opt/aws/bin/cfn-init -s ${AWS::StackId} -r LaunchConfig --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
             # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
-            /opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
+            # /opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
+            mkdir /carve/
+            echo "0.0.0.0" > /carve/carve.cfg
+            echo "import os" > /carve/updater.py
+            echo "import socket" >> /carve/updater.py
+            echo "import json" >> /carve/updater.py
+            echo "import ipaddress" >> /carve/updater.py
+            echo "" >> /carve/updater.py
+            echo "'''" >> /carve/updater.py
+            echo "Basic socket server to receive data on port 8008" >> /carve/updater.py
+            echo "It is used to update the carve config beacon data" >> /carve/updater.py
+            echo "Data must be submitted as byte encoded valid json" >> /carve/updater.py
+            echo "'''" >> /carve/updater.py
+            echo "" >> /carve/updater.py
+            echo "def socket_server():" >> /carve/updater.py
+            echo "    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:" >> /carve/updater.py
+            echo "        s.bind(('0.0.0.0', 8008))" >> /carve/updater.py
+            echo "        s.listen()" >> /carve/updater.py
+            echo "        while True:" >> /carve/updater.py
+            echo "            conn, addr = s.accept()" >> /carve/updater.py
+            echo "            with conn:" >> /carve/updater.py
+            echo "                print('Connected by', addr)" >> /carve/updater.py
+            echo "                while True:" >> /carve/updater.py
+            echo "                    data = conn.recv(1024)" >> /carve/updater.py
+            echo "                    if not data:" >> /carve/updater.py
+            echo "                        break" >> /carve/updater.py
+            echo "                    result = received(data)" >> /carve/updater.py
+            echo "                    if result == 'success':" >> /carve/updater.py
+            echo "                        conn.sendall(data)" >> /carve/updater.py
+            echo "                    else:" >> /carve/updater.py
+            echo "                        conn.sendall(bytes(result.encode()))" >> /carve/updater.py
+            echo "" >> /carve/updater.py
+            echo "def received(data):" >> /carve/updater.py
+            echo "    try:" >> /carve/updater.py
+            echo "        post = (json.loads(data))" >> /carve/updater.py
+            echo "    except:" >> /carve/updater.py
+            echo "        post = {}" >> /carve/updater.py
+            echo "        result = 'socket did not receive json data'" >> /carve/updater.py
+            echo "    # process based on json data" >> /carve/updater.py
+            echo "    try:" >> /carve/updater.py
+            echo "        if 'beacons' in post:" >> /carve/updater.py
+            echo "            beacons = post['beacons'].split(',')" >> /carve/updater.py
+            echo "            with open('new.cfg', 'a') as file:" >> /carve/updater.py
+            echo "                for beacon in beacons:" >> /carve/updater.py
+            echo "                    if valid_addr(beacon):" >> /carve/updater.py
+            echo "                        file.write(f'{beacon}\n')" >> /carve/updater.py
+            echo "                    else:" >> /carve/updater.py
+            echo "                        pass" >> /carve/updater.py
+            echo "            os.replace('new.cfg', 'carve.cfg')" >> /carve/updater.py
+            echo "            result = 'success'" >> /carve/updater.py
+            echo "        else:" >> /carve/updater.py
+            echo "            result = f'beacons not in post: {post}'" >> /carve/updater.py
+            echo "    except:" >> /carve/updater.py
+            echo "        result = 'try exception'" >> /carve/updater.py
+            echo "    return result" >> /carve/updater.py
+            echo "" >> /carve/updater.py
+            echo "def valid_addr(ipaddr):" >> /carve/updater.py
+            echo "    # validate if string is a valid IP address" >> /carve/updater.py
+            echo "    try:" >> /carve/updater.py
+            echo "        ip = ipaddress.ip_address(ipaddr)" >> /carve/updater.py
+            echo "        return True" >> /carve/updater.py
+            echo "    except ValueError:" >> /carve/updater.py
+            echo "        return False" >> /carve/updater.py
+            echo "    except:" >> /carve/updater.py
+            echo "        return False" >> /carve/updater.py
+            echo "" >> /carve/updater.py
+            echo "if __name__ == '__main__':" >> /carve/updater.py
+            echo "    socket_server()" >> /carve/updater.py
+            echo "
             # create carve testing script
             echo '#!/bin/bash' > /carve/carve.sh
             echo 'while true; do' >> /carve/carve.sh
@@ -272,7 +307,7 @@ Resources:
             # start update server to receive beacon address updates
             docker run -d --restart unless-stopped --name updater -p 8008:8008 -v "/carve:/carve" -w /carve python:slim python updater.py
             # All done so signal success
-            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource LaunchConfig --region ${AWS::Region} || echo 'cfn-signal error - stack is probably complete'
+            # /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource LaunchConfig --region ${AWS::Region} || echo 'cfn-signal error - stack is probably complete'
 
   InstanceSecurityGroup:
     Type: AWS::EC2::SecurityGroup
